apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeservice-deployment
  labels:
    name: timeservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timeservice
  template:
    metadata:
      labels:
        app: timeservice
    spec:
      containers:
        - name: timeservice
          image: timeservice:1.0
          ports:
            - containerPort: 8080
