apiVersion: v1
kind: Service
metadata:
  name: timeservice-service
  labels:
    name: timeservice-service
spec:
  type: ClusterIP
  selector:
    app: timeservice
  ports:
    - port: 80
      name: http
      targetPort: 8080
